split data-navigator-tap
hkjels/data-navigator.el pull request #6
Opened 2024-12-18 13:48 UTC by a13

I hope this one won't break your own workflow.

2024-12-18 14:32 UTC, hkjels commented
Looks really good. With the changes mentioned, I think this could be merged.
I would however like to research if integrating with Cider is doable as I think that would have some added benefit. https://github.com/hkjels/data-navigator.el/issues/7

2024-12-18 14:39 UTC, a13 commented
Sorry, what changes are you talking about?

2024-12-18 19:51 UTC, hkjels commented
I made some review comments

2024-12-19 12:31 UTC, hkjels requested changes

2024-12-19 12:31 UTC, hkjels commented on data-navigator-tap.el
> +;; run M-x tap-socket-start
I presume this should be changed to `data-navigator-tap-mode`.

2024-12-19 12:31 UTC, hkjels commented on data-navigator-tap.el
> +    (data-navigator-from-input data)))
We could send "tap>" as the second parameter here?  I'm thinking about making the Clojure side of this a library as well. At that point, we could even send the filename and line-number perhaps

2024-12-19 13:02 UTC, a13 commented on data-navigator-tap.el
> +    (data-navigator-from-input data)))
I'll take a look

2024-12-19 18:07 UTC, a13 commented on data-navigator-tap.el
> +;; run M-x tap-socket-start
fixed, thanks

2024-12-19 18:12 UTC, a13 commented on data-navigator-tap.el
> +    (data-navigator-from-input data)))
> We could send "tap>" as the second parameter here?

@hkjels can we postpone this one for now? 

> I'm thinking about making the Clojure side of this a library as well. 

I agree, but I think we need to discuss the best way to implement it (together with Cider integration etc)

2024-12-20 08:16 UTC, merged